//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bills
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bills()
        {
            this.Zakazs = new HashSet<Zakazs>();
        }
    
        public int Bill_ID { get; set; }
        public int FK_TypeOplati { get; set; }
        public int FK_Client { get; set; }
        public int FK_TypeDostavki { get; set; }
        public string DateBill { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual TypeDostavkis TypeDostavkis { get; set; }
        public virtual TypeOplatis TypeOplatis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakazs> Zakazs { get; set; }
    }
}
