//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnicks
    {
        public int Sotrudnick_ID { get; set; }
        public int FK_Dolznost { get; set; }
        public int FK_SNM_Sortudnick { get; set; }
        public int FK_LoginPass { get; set; }
    
        public virtual Dolznostis Dolznostis { get; set; }
        public virtual LoginPasses LoginPasses { get; set; }
        public virtual SNM_Sortudnicks SNM_Sortudnicks { get; set; }
    }
}
