//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unitazs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Unitazs()
        {
            this.Zakazs = new HashSet<Zakazs>();
        }
    
        public int Unitaz_ID { get; set; }
        public string UnitazName { get; set; }
        public int FK_UnitazType { get; set; }
        public decimal UnitazPrice { get; set; }
        public int FK_CountryProizvodstva { get; set; }
    
        public virtual CountryProizvodstvas CountryProizvodstvas { get; set; }
        public virtual UnitazTypes UnitazTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakazs> Zakazs { get; set; }
    }
}
