//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laba5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakazs
    {
        public int Zakaz_ID { get; set; }
        public int FK_Unitaz { get; set; }
        public int FK_Bill { get; set; }
        public int KolvoUnitaz { get; set; }
        public decimal PriceBill { get; set; }
    
        public virtual Bills Bills { get; set; }
        public virtual Unitazs Unitazs { get; set; }
    }
}
